### ISSUE TITLE
Facing erro

### ISSUE THREAD

**Issue by finn-dev** [AgoraIO-Usecase/AgoraChat-web#49]
Hi,

I just followed same as in description
npx create-react-app
npm install agora-chat-uikit

then run the project, but i am getting this error
![image](https://user-images.githubusercontent.com/67330526/201248155-a430751f-2206-4e6e-b386-bc7f2864ea3c.png)

any idea?

Regards

**Comment by myZhangDong** [comment]
You can try installing chat sdk：npm i agora-chat
