### ISSUE TITLE
Add an option in setting to let user change chat language 

### ISSUE THREAD

**Issue by khalil-alsous** [AgoraIO-Usecase/AgoraChat-web#51]
**I want to give the user option to change chat language by select the language he want from setting tab .. is that possible ??**

> This is similar to what I mean 
![lang](https://user-images.githubusercontent.com/81516433/222141446-44088243-9e68-447d-9c0b-cdd94e0882ed.png)

**Comment by ycj3** [comment]
Maybe you mean `Translate messages` ? 
Maybe this link is helpful: https://docs.agora.io/en/agora-chat/client-api/messages/translate-messages?platform=web
