### ISSUE TITLE
Css issue

### ISSUE THREAD

**Issue by sreekanthThadigot** [AgoraIO-Usecase/AgoraChat-web#52]
Hi, 

 I am facing an issue when i try to move Agorachat code into an existing next.js project...
 Facing an issue with the css.... Please check...

![Screenshot 2023-04-23 102538 (1)](https://user-images.githubusercontent.com/81404394/233821783-6a090273-dcc7-4f9a-8638-badb47396ea3.jpg)

**Comment by myZhangDong** [comment]
Currently agora-chat-uikit doesn't export the css file, so you can try moving uikit from node_modules to the project source
